apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
<<<<<<< HEAD
        image: us-east4-docker.pkg.dev/YOUR_PROJECT_ID/my-repository/blue:v1.0
=======
        image: us-east1-docker.pkg.dev/qwiklabs-gcp-04-dc0fafa73b5e/my-repository/blue:v2.0
>>>>>>> 566e7b149c3f154880464e5a7e6635d5ed0b575e
        ports:
        - containerPort: 8080
